# Generated by Django 5.0.6 on 2024-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_board_is_active_collaborator_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
